HOSTNAME = 'xxx'
PORT = '3306'
DATABASE = 'xxx'
USERNAME = 'xxx'
PASSWORD = '***'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
